pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Stair-Rover
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.frame59.com/
#
# 2. URL of this page
url:              http://rllaverias.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Stair-Rover
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/1lL816L
  #
  # URL of a cover photo of your project
  cover_image:    http://www.google.com/search?q=color+static&tbm=isch&tbs=simg:CAQSYRpfCxCo1NgEGgIICAwLELCMpwgaOAo2CAESEAwPmwKaApMBvAGAArIBsQEaIPiuNEm8gBeV08ayqOy5yf3FP45dmFhyecrqh318f69lDAsQjq7-CBoKCggIARIE_1WTKxww&sa=X&ei=WM_VUuvvK6qysQTCroDwBA&ved=0CCcQwg4oAA&biw=1363&bih=680&dpr=0.9#facrc=_&imgrc=MROtDaJCecZGmM%253A%3BZVXPCjOMqfoxKM%3Bhttps%253A%252F%252Flh6.googleusercontent.com%252F-7ezzaWuFg74%252FUf3XnGIgjqI%252FAAAAAAAAACI%252FMQ0C69QdDOM%252Fs0-d%252FStatic_2048.jpg%3Bhttps%253A%252F%252Fplus.google.com%252F110539594894811296287%3B1280%3B720
  #
  # Use a one-liner to describe your project
  description:    Stair-Rover is a longboard that glides down stairs with a blast.
#
# 4. Your Twitter handle
twitter_handle:   StairRover
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is the Stair-Rover team greeting from London. <br />
  First of all, thank you for signing up to our mailing list. <br />
  Here's to tell you that our project is now live on Kickstarter,
  and now we have to count on your support to not only back the project, but also share the love. ♥
